apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: check-ec2-finops-compliance
spec:
  rules:
    - name: check-ec2-instance-size
      match:
        all:
        - (planned_values.root_module.resources[?type=='akp_instance'].values.argocd_cm[] | length(@) > `0`): true
      assert:
        any:
        - message: Do not allow anonymous users for ArgoCD Instances
          check:
            planned_values:
              root_module:
                ~.(resources[?type=='akp_instance']):
                  values:
                    argocd_cm:
                      (users.anonymous.enabled == 'true'): true
