apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  destination:
    name: eks-everything-as-code
    namespace: kyverno
  source:
    path: policies/kubernetes
    repoURL: https://github.com/back-stack/everything-as-code.git
    targetRevision: HEAD
