apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: argo-application-field-validation
spec:
  rules:
    - name: source-path-chart
      match:
        all:
        - kind: Application
      assert:
        all:
        - message: spec.source.path OR spec.source.chart should be specified but never both.
          check:
            spec:
              source:
                ((path || '') != '' && (chart || '') != ''): false
    - name: destination-server-name
      match:
        any:
        - kind: Application
      assert:
        all:
        - message: spec.destination.server OR spec.destination.name should be specified but never both.
          check:
            spec:
              destination::
                ((server || '') != '' && (name || '') != ''): false
