apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    name: eks-everything-as-code
    namespace: argocd
  source:
    repoURL: 'https://github.com/back-stack/everything-as-code'
    path: argo-cd/apps
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
