name: NCTL Scan ArgoCD Applications
run-name: ${{ github.actor }} has triggered Scan Action 🚀
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"

jobs:
  NCTL-Scan-ArgoCD-Apps:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: nctl-scan-installer
        uses: nirmata/action-install-nctl-scan@v0.0.3

      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: Check nctl version
        run: nctl version

      - name: NCTL Scan - ArgoCD Apps
        # cd config-files/terraform
        # terraform init
        # terraform plan -out tfplan.binary
        # terraform show -json tfplan.binary | jq > payload.json
        run: nctl scan kubernetes --policies policies/argocd/check-argocd-application.yaml --resources argo-cd/apps

      - run: echo "🍏 This job's status is ${{ job.status }}."
